version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste123
    volumes:
      - ./data:/data/db
  back-end:
    build: "."
    container_name: node-container
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
    depends_on:
      - mongo